export const constants = {
  name: "Tushar Goel",
  brandName: "TG",
  about: "About",
  skills: "Skills",
  experience: "Experience",
  skillsHeading: "Technologies & Languages I am ",
  skillsExperienced: "Skilled & Experienced ",
  linkedin: "LinkedIn",
  email: "Email",
  github: "GitHub",
  resume: "Resume",
  developedBy: "Developed by ",
  developerName: "tushargoel",
  linkedinLink: "https://www.linkedin.com/in/tsage1234",
  emailId: "tushargoel15@gmail.com",
  resumeLink: "",
  githubLink: "https://github.com/TusharGoelGitsHub",
  journey: "Journey ",
  soFar: " so far",
  in: "in",
};
